Josh
klgriffen96/summer23_data624 pull request #2
Opened 2023-06-07 15:43 UTC by josh1den

2023-06-07 15:46 UTC, josh1den commented
@aliceafriedman -- can you show me how to merge this file with every change *except* for the line: TAKE ALL NEW COMMITS EXCEPT THIS ONE

Gonna keep trying to figure it out. No rush!

2023-06-07 16:29 UTC, josh1den commented on hw_1/iden_data624_hw1.Rmd
> +sprintf('gas frequency = %d', frequency(gas))
exclude

2023-06-07 16:29 UTC, josh1den commented on hw_1/iden_data624_hw1.Rmd
>  Gold data is yearly, Wool data is quarterly, and Gas data is monthly.
exclude

2023-06-13 00:15 UTC, aliceafriedman commented on hw_1/iden_data624_hw1.Rmd
> +sprintf('gas frequency = %d', frequency(gas))
Sorry it's not a super automated thing -- basically you have to have someone review and say, please revise and rollback this commit! 

OR if there's a conflict (which is when there are *competing* commits you can go in line by line and resolve the conflict.

2023-06-13 00:17 UTC, aliceafriedman requested changes
So basically you can "request changes' there's a way to "cherry pick" in the command line also...

2023-06-16 23:25 UTC, closed without merging